title: Junjie Ma's Homepage
page-top-title: Junjie Ma
top-section-bg-text: Integrated Circuit Engineering
home-subtitle: Junjie Ma&ensp;|&ensp;马骏杰
copyright-text: '&copy; Junjie Ma 2023-2025. All Rights Reserved.'
